mysql:
  build: .
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=fizzye
    - MYSQL_DATABASE=arthurius
  volumes:
    - ./conf:/etc/mysql/conf.d
    - ./arthurius_export.sql:/docker-entrypoint-initdb.d/init.sql